name: intellensense
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.4
  flutter_zoom_drawer: ^2.1.1
  rating_dialog: ^2.0.0
  timelines: ^0.1.0
  getwidget: ^3.0.1
  http: ^0.13.4
  carousel_pro: ^1.0.0
  foundation_flutter: ^0.2.0
  bubble_tab_indicator: ^0.1.6
  avatars: ^2.0.0
  font_awesome_flutter: ^10.1.0
  google_sign_in:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  shared_preferences:
  image_picker:
  cached_network_image:
  fluttertoast:
  intl:
  firebase_messaging:
  photo_view:
  firebase_core:
  provider:
  country_code_picker:
  equatable:
  tap_to_expand: ^0.6.1
  flip_card: ^0.6.0
  popup_card: ^0.1.0
  quickalert: ^1.0.0
  cool_alert: ^1.1.0
  settings_ui: ^2.0.2
  dropdown_button2: ^1.9.2
  google_maps_flutter: ^2.2.3
  expansion_tile_card: ^2.0.0
  flutter_svg: ^2.0.3
  fl_chart: ^0.35.0
  sleek_circular_slider: ^2.0.1
  youtube: ^1.0.1
  text_scroll: ^0.1.2
  auto_size_text: ^3.0.0
  marquee: ^2.2.3
  marquee_text: ^2.5.0+1
  animated_bottom_navigation_bar: ^1.2.0
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/Image/
    - assets/ChatImg/
    - assets/svg/
    - assets/icons/Home-Iocn.png
    - assets/icons/Candidature Analysis.png
    - assets/icons/location.png
    - assets/icons/communicationChannel.png
    - assets/icons/Form.png
    - assets/icons/faceEmotiondxp.png
    - assets/icons/compareIconB.png
    - assets/icons/ScoreCard.png
    - assets/icons/fb.png
    - assets/icons/newspaperdxp.png
    - assets/NotificationIcons/analyticsShowCard.png
    - assets/NotificationIcons/Open_Docs_Icon.png
    - assets/NotificationIcons/GridDB.png
    - assets/NotificationIcons/Pivot-Unpivot_Icon.png
    - assets/NotificationIcons/Tree.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
